imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: elasticsearch.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# Services directly link to the config
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:   ~
    session:
        handler_id: snc_redis.session.handler
    fragments: ~
    http_method_override: true
    assets:
        version_format: '%%s?version=%%s'
        packages:
            css:
                version: '%app_version%'
            js:
                version: '%app_version%'
            image:
                version: '%app_version%'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - form/fields.html.twig
    globals:
        fasta_generator: '@AppBundle\Utils\FastaGenerator'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Doctrine extensions
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

# ReCaptcha
ewz_recaptcha:
    public_key:  '%env(RECAPTCHA_PUBLIC_KEY)%'
    private_key: '%env(RECAPTCHA_PRIVATE_KEY)%'
    locale_key:  '%kernel.default_locale%'

# Redis
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://%redis_host%'
    session:
        client: default

# RabbitMQ
old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     '%rabbitmq_port%'
            user:     '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
    producers:
        blast:
            connection:       default
            exchange_options: {name: 'blast', type: direct}
            enable_logger: true
        multiple_alignment:
            connection:       default
            exchange_options: {name: 'multiple-alignment', type: direct}
            enable_logger: true
    consumers:
        blast:
            connection:       default
            exchange_options: {name: 'blast', type: direct}
            queue_options:    {name: 'blast'}
            callback:         AppBundle\Utils\BlastConsumer
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
            enable_logger: true
        multiple_alignment:
            connection:       default
            exchange_options: {name: 'multiple-alignment', type: direct}
            queue_options:    {name: 'multiple-alignment'}
            callback:         AppBundle\Utils\MultipleAlignmentConsumer
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
            enable_logger: true
