cluster.name: "grycii-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

# Disable xpack security (authentification)
# Details: https://www.elastic.co/guide/en/x-pack/5.2/security-settings.html
xpack.security.enabled: false

# Do not use in prod, only dev for debug with ES-Head
http.cors.enabled: true
http.cors.allow-origin: "*"
